config/routes.rb
Ritly::Application.routes.draw do
  root 'home#index'
  resources :urls
  get '/:some_totally_random_value', to: 'urls#redirectors'
  get '/:some_totally_random_value/preview', to: 'urls#preview'

  

end

app/models/url.rb
class Url < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  
	def index
		@urls = Url.all
	end
  def new
  	@url = Url.new
  end

  def create
  	safe_url = params.require(:url).permit(:link)
  	@url = Url.new(safe_url)
  	@url.hash_code = rand(100000)
  	
  	if @url.save
  		redirect_to url_path(@url)
  	end
	end

  def show
  	@url = Url.find(params[:id])
  end

  def redirectors
  	@url = Url.find_by hash_code: params[:some_totally_random_value]
    if @url
      redirect_to @url.link
    else
      redirect_to root_path
    end
  end

  def preview
  	@url = Url.find_by hash_code: params[:some_totally_random_value]
    if @url
      redirect_to @url.link
    else
      redirect_to root_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/home/index.html.erb
<h2>Welcome to Ritly!</h2>

<p><%= link_to 'Click here to generate a new url code.', new_url_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ritly</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/create.html.erb
<h1>Urls#create</h1>
<p>Find me in app/views/urls/create.html.erb</p>

app/views/urls/index.html.erb
<h1>Show all URLs</h1>

<% @urls.each do |url|%>

	<%= link_to url_path(url) do %>

		<p>Link: <%= url.link %> | <%= url.hash_code %></p>

	<% end %>

<% end %>

<%= link_to 'Generate another code.', new_url_path %>

app/views/urls/new.html.erb
<h2>Enter your URL link below.</h2>

<%= form_for @url do |f| %>
	<%= f.label :link %>
	<%= f.text_field :link %>
	<%= f.submit %>
<% end %>

app/views/urls/preview.html.erb
<h1>Code: <%= @url.hash_code %></h1>
<p>This code will take you to <%= @url.link %></p>
<%= link_to "Click Here", @url.link %> to continue

app/views/urls/show.html.erb
<h2>Sweet!</h2>

<p>
	Your randomly generated code is: <%= @url.hash_code %>
</p>

<p>
	You can go to 
	<%= link_to @url.link do %> 
		localhost:3000/<%= @url.hash_code %>
	<% end %>
	<span>to visit your url.</span>
</p>

<p>
	<%= link_to 'Generate another code.', new_url_path %>
</p>